# fly.toml file generated for fleetbox on 2022-06-14T22:53:48-05:00

app = "fleetbox-staging"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[deploy]
  release_command = "post-deploy"

[env]
  PORT = "8080"
  PRIMARY_REGION = "dfw"
  RAILS_ENV = "staging"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[statics]]
  guest_path = "/app/public"
  url_prefix = "/"
