volumes:
  database:

services:
  database:
    image: postgres:14.3-alpine
    expose:
      - "5432:5432"
    environment:
      POSTGRES_DB: rails_development
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
    volumes:
      - "database:/var/lib/postgresql/data"
  web:
    build:
      context: ..
      dockerfile: Dockerfile
      target: gems
      args:
        RAILS_ENV: development
        BUNDLE_WITHOUT: ""
        BUNDLE_PATH: ""
    environment:
      RAILS_ENV: development
      DATABASE_URL: "postgres://rails:password@database:5432/rails_development"
    links:
      - database
    command: local-dev-server
    volumes:
      - ../:/app
    ports:
      - "127.0.0.1:3000:3000"