services:
  database:
    image: postgres:14.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rails_test
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U rails -d rails_test" ]
      interval: 1s
      timeout: 1s
      retries: 25
  tests:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        RAILS_ENV: test
        BUNDLE_WITHOUT: development
        EXTRA_PROD_PACKAGES: chromium chromium-driver
    environment:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@database:5432/rails_test"
      FLEETBOX_DOCKER_TESTS: yes
    links:
      - database
    depends_on:
      database:
        condition: service_healthy
    command: make local-test
    volumes:
      - ../junit:/app/junit