services:
  database:
    image: postgres:14.3-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: rails_test
      POSTGRES_USER: rails
      POSTGRES_PASSWORD: password
  tests:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        RAILS_ENV: test
        BUNDLE_WITHOUT: development
        EXTRA_PROD_PACKAGES: firefox-esr
    environment:
      RAILS_ENV: test
      DATABASE_URL: "postgres://rails:password@database:5432/rails_test"
    links:
      - database
    command: make sleep-then-local-test
    volumes:
      - ../junit:/app/junit